extern CAMLprim value caml_gr_plot(value vx, value vy);
extern CAMLprim value caml_gr_moveto(value vx, value vy);
extern CAMLprim value caml_gr_current_x(void);
extern CAMLprim value caml_gr_current_y(void);
extern CAMLprim value caml_gr_lineto(value vx, value vy);
extern CAMLprim value caml_gr_draw_rect(value vx, value vy, value vw, value vh);
extern CAMLprim value caml_gr_draw_text(value text,value x);
extern CAMLprim value caml_gr_fill_rect(value vx, value vy, value vw, value vh);
extern CAMLprim value caml_gr_sound(value freq, value vdur);
extern CAMLprim value caml_gr_point_color(value vx, value vy);
extern CAMLprim value caml_gr_circle(value x,value y,value radius);
extern CAMLprim value caml_gr_set_window_title(value text);
extern CAMLprim value caml_gr_draw_arc(value *argv, int argc);
extern CAMLprim value caml_gr_draw_arc_nat(int vx, int vy, int vrx, int vry, int vstart, int vend);
extern CAMLprim value caml_gr_set_line_width(value vwidth);
extern CAMLprim value caml_gr_set_color(value vcolor);
extern CAMLprim value caml_gr_show_bitmap(value filename,int x,int y);
extern CAMLprim value caml_gr_get_mousex(void);
extern CAMLprim value caml_gr_get_mousey(void);
extern CAMLprim value caml_gr_set_font(value fontname);
extern CAMLprim value caml_gr_set_text_size (value sz);
extern CAMLprim value caml_gr_draw_char(value chr);
extern CAMLprim value caml_gr_draw_string(value str);
extern CAMLprim value caml_gr_text_size(value str);
extern CAMLprim value caml_gr_fill_poly(value vect);
extern CAMLprim value caml_gr_fill_arc(value *argv, int argc);
extern CAMLprim value caml_gr_fill_arc_nat(int vx, int vy, int vrx, int vry, int vstart, int vend);
extern CAMLprim value caml_gr_create_image(value vw, value vh);
extern CAMLprim value caml_gr_blit_image (value i, value x, value y);
extern CAMLprim value caml_gr_draw_image(value i, value x, value y);
extern CAMLprim value caml_gr_make_image(value matrix);
extern CAMLprim value caml_gr_dump_image (value img);
extern CAMLprim value caml_gr_wait_event(value eventlist) /* ML */;
extern CAMLprim value caml_gr_clear_graph(void);;
extern CAMLprim value caml_gr_open_graph(value arg);
extern CAMLprim value caml_gr_close_graph(void);
extern CAMLprim value caml_gr_clear_graph(void);
extern CAMLprim value caml_gr_size_x(void);
extern CAMLprim value caml_gr_size_y(void);
extern CAMLprim value caml_gr_resize_window (value vx, value vy);
extern CAMLprim value caml_gr_synchronize(void);
extern CAMLprim value caml_gr_display_mode(value flag);
extern CAMLprim value caml_gr_remember_mode(value flag);
extern CAMLprim value caml_gr_sigio_signal(value unit);
extern CAMLprim value caml_gr_sigio_handler(void);

typedef enum {FALSE, TRUE} BOOL;
typedef unsigned char BYTE;

extern CAMLprim value caml_gr_wait_event_blocking(long);
extern value caml_gr_wait_event_poll(void);
extern value caml_gr_window_id(void);
extern void gr_fail(char *fmt, char *arg);
extern int gr_open_graph_internal(value);
extern void gr_check_open(void);
extern value caml_gr_open_subwindow(value vx, value vy, value width, value height);
extern value caml_gr_close_subwindow(value wid);

